version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
         command: npx cypress run --record --key 7e18f213-8151-4974-851e-9ddbe4ac75f5
         record: true
        
      